#include <iostream>
using namespace std;


int main(){
    
    // cout << "Hello World!" << endl;

    // string name;

    // getline(cin,name);

    // cout << "Hello " << name << endl;

    double numberOne , numberTwo;

    cout << "Enter the first number: ";
    cin >> numberOne;

    cout << "Enter the second number: ";
    cin >> numberTwo;

    cout << "The sum of " << numberOne << " and " << numberTwo << " is " << numberOne + numberTwo << endl;
    
    return 0;
}